apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
  labels:
    app: demo1
  namespace: demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - image: 802924987857.dkr.ecr.ap-south-1.amazonaws.com/demo1:latest
        imagePullPolicy: Always
        name: demo1
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: demo1
  namespace: demo1
spec:
  selector:
    app: demo1
  ports:
    - name: http 
      protocol: TCP
      port: 8080
